Repository ThakeeNathees/pocketlang, pull requests merged in 2021-06, with the labels that each got.

#40 VM refactor for REPL [1/3]
  cli/main.c
  docs/try/main.c
  src/buffers.c
  src/buffers.h
  src/compiler.c
  src/debug.c
  src/include/pocketlang.h
  src/opcodes.h
  src/var.c
  src/vm.c
  src/vm.h
Labels: refector

#43 Refactor for REPL support [2/3]
  build/build.bat
  cli/TODO.txt
  cli/main.c
  src/common.h
  src/compiler.c
  src/compiler.h
  src/core.c
  src/core.h
  src/debug.c
  src/include/pocketlang.h
  src/opcodes.h
  src/var.c
  src/var.h
  src/vm.c
  src/vm.h
Labels: refector

#44 REPL refactor [3/3]
  cli/TODO.txt
  cli/main.c
  cli/modules/path.c
  src/common.h
  src/compiler.c
  src/core.c
  src/debug.c
  src/include/pocketlang.h
  src/opcodes.h
  src/utils.c
  src/var.c
  src/var.h
  src/vm.c
  src/vm.h
Labels: refector

#47 REPL implementation.
  README.md
  build/Makefile
  build/SConstruct
  build/build.bat
  cli/all.c
  cli/common.h
  cli/main.c
  cli/modules/path.c
  cli/repl.c
  cli/uitls.c
  cli/utils.h
  docs/TODO.txt
  src/include/pocketlang.h
  src/pk_buffers.h
  src/pk_common.h
  src/pk_compiler.c
  src/pk_compiler.h
  src/pk_core.c
  src/pk_core.h
  src/pk_debug.c
  src/pk_debug.h
  src/pk_opcodes.h
  src/pk_utils.c
  src/pk_utils.h
  src/pk_var.c
  src/pk_var.h
  src/pk_vm.c
  src/pk_vm.h
  test/benchmark/list/list.pk
  test/benchmark/list/list.py
  test/benchmark/list/list.rb
  test/run.py
Labels: enhancement, implementation, refector

#48 Set pointer to first byte of memory block when `realloc()`'d
  cli/repl.c
  cli/utils.c
  cli/utils.h
  src/pk_common.h
  src/pk_compiler.h
  src/pk_core.c
  src/pk_vm.c
Labels: bug

#49 Fix more typos in cli/common.h
  cli/common.h
Labels: enhancement

#50 Cleanup more typos from cli/ source files
  cli/all.c
  cli/repl.c
Labels: enhancement

#51 Core attributes refactored and added tests
  cli/common.h
  cli/modules/path.c
  cli/repl.c
  cli/utils.c
  cli/utils.h
  docs/TODO.txt
  src/include/pocketlang.h
  src/pk_buffers.h
  src/pk_common.h
  src/pk_compiler.c
  src/pk_compiler.h
  src/pk_core.c
  src/pk_debug.c
  src/pk_opcodes.h
  src/pk_var.c
  src/pk_var.h
  test/run.py
  tests/benchmark/factors/factors.js
  tests/benchmark/factors/factors.pk
  tests/benchmark/factors/factors.py
  tests/benchmark/factors/factors.rb
  tests/benchmark/factors/factors.wren
  tests/benchmark/fib/fib.pk
  tests/benchmark/fib/fib.py
  tests/benchmark/fib/fib.rb
  tests/benchmark/fib/fib.wren
  tests/benchmark/list/list.pk
  tests/benchmark/list/list.py
  tests/benchmark/list/list.rb
  tests/benchmark/loop/loop.js
  tests/benchmark/loop/loop.pk
  tests/benchmark/loop/loop.py
  tests/benchmark/loop/loop.rb
  tests/benchmark/loop/loop.wren
  tests/benchmark/primes/primes.pk
  tests/benchmark/primes/primes.py
  tests/benchmark/primes/primes.rb
  tests/benchmark/primes/primes.wren
  tests/check.py
  tests/examples/brainfuck.pk
  tests/examples/fib.pk
  tests/examples/fizzbuzz.pk
  tests/examples/helloworld.pk
  tests/examples/palette.pk
  tests/examples/pi.pk
  tests/examples/prime.pk
  tests/lang/basics.pk
  tests/lang/controlflow.pk
  tests/lang/core.pk
  tests/lang/fibers.pk
  tests/lang/functions.pk
  tests/lang/import.pk
  tests/lang/import/all_import.pk
  tests/lang/import/module.pk
  tests/tests.py
Labels: implementation, refector

#58 Fix #56: Implement the `cos()` and `tan()` math functions
  src/pk_core.c
  tests/lang/core.pk
Labels: implementation

#61 Disassembler public api for debugging.
  cli/main.c
  docs/TODO.txt
  src/pk_common.h
  src/pk_compiler.c
  src/pk_core.c
  src/pk_debug.c
  src/pk_debug.h
  src/pk_var.c
  src/pk_var.h
  src/pk_vm.c
  tests/examples/pi.pk
  tests/lang/controlflow.pk
Labels: implementation

#59 Fix #54: Add bitwise OR operator and make it available in PKVM
  src/pk_core.c
  src/pk_core.h
  src/pk_vm.c
  tests/lang/basics.pk
  tests/lang/core.pk
Labels: implementation

#66 Cleanup some typos from the `include/pocketlang.h` header file
  src/include/pocketlang.h
Labels: documentation

#67 import name bind bug fix
  src/pk_compiler.c
  src/pk_core.c
  src/pk_opcodes.h
  src/pk_vm.c
  tests/benchmark/toc/toc.pk
  tests/lang/toc.pk
Labels: bug

#69 Operator &= implemented
  docs/TODO.txt
  src/pk_compiler.c
  tests/lang/basics.pk
Labels: implementation

#71 Operators |= and ^= implemented
  src/pk_compiler.c
  tests/lang/basics.pk
Labels: implementation

#73 Fix typos + rename variables
  README.md
  docs/TODO.txt
  docs/generate.py
  docs/pages/Getting-Started/build-from-source.md
  docs/pages/Getting-Started/learn-in-15-minutes.md
  docs/pages/Language-API/modules.md
  docs/static/template.html
  src/include/pocketlang.h
  src/pk_buffers.h
  src/pk_common.h
  src/pk_compiler.c
  src/pk_compiler.h
  src/pk_core.c
  src/pk_opcodes.h
  src/pk_utils.h
  src/pk_var.c
  src/pk_var.h
  src/pk_vm.c
  src/pk_vm.h
  tests/examples/brainfuck.pk
Labels: documentation, refector

#72 bin hex literals implemented
  README.md
  src/pk_compiler.c
  src/pk_core.c
  src/pk_vm.h
  tests/lang/basics.pk
  tests/lang/controlflow.pk
  tests/lang/core.pk
  tests/lang/fibers.pk
  tests/lang/functions.pk
  tests/lang/import.pk
  tests/lang/toc.pk
Labels: implementation

#80 pk_core: implement list addition
  src/pk_buffers.h
  src/pk_core.c
  src/pk_var.c
  src/pk_var.h
  tests/lang/basics.pk
Labels: implementation

#81 tests: allow tests to be called from anywhere
  .github/workflows/build.yml
  tests/check.py
  tests/tests.py
Labels: enhancement, refector

#75 Changed the elif notation to else if
  docs/pages/Getting-Started/learn-in-15-minutes.md
  docs/static/prism/prism.js
  src/pk_compiler.c
  tests/examples/brainfuck.pk
  tests/examples/fizzbuzz.pk
  tests/lang/controlflow.pk
Labels: refector

#83 Improve REPL to use a byte buffer with `fgetc()` to read line
  cli/repl.c
Labels: enhancement

#87 Renamed GC functions rename for documenting.
  cli/repl.c
  src/pk_compiler.c
  src/pk_var.c
  src/pk_var.h
  src/pk_vm.c
  src/pk_vm.h
Labels: refector

#90 Makefile: compile objects individually, then link
  .github/workflows/build.yml
  .gitignore
  Makefile
  SConstruct
  build.bat
  build/.gitignore
  build/Makefile
Labels: portability, refector

#91 SConstruct file removed and build scripts refactored
  .gitignore
  SConstruct
  build.bat
  tests/check.py
Labels: refector

#86 Add support for bitwise NOT (~) operator to pocketlang
  src/pk_core.c
  src/pk_core.h
  src/pk_vm.c
  tests/lang/basics.pk
Labels: implementation

#95 [WIP] Docstring extracted and `help()` function added
  .github/workflows/build.yml
  README.md
  src/include/pocketlang.h
  src/pk_common.h
  src/pk_compiler.c
  src/pk_core.c
  src/pk_var.c
  src/pk_var.h
  tests/check.py
  tests/lang/basics.pk
  tests/lang/controlflow.pk
  tests/tests.py
Labels: documentation, implementation

#98 __file__ variable added to scripts
  README.md
  cli/main.c
  cli/modules/path.c
  docs/TODO.txt
  docs/generate.py
  docs/try/main.c
  src/include/pocketlang.h
  src/pk_common.h
  src/pk_compiler.c
  src/pk_core.c
  src/pk_var.c
  src/pk_var.h
  tests/check.py
  tests/tests.py
Labels: enhancement

#100 yet another minor refactor
  cli/all.c
  cli/modules/path.c
  cli/modules/thirdparty/cwalk/LICENSE.md
  cli/modules/thirdparty/cwalk/cwalk.c
  cli/modules/thirdparty/cwalk/cwalk.h
  cli/modules/thirdparty/dirent/LICENSE
  cli/modules/thirdparty/dirent/dirent.h
  docs/TODO.txt
  src/pk_compiler.c
  src/pk_core.c
  src/pk_debug.c
  src/pk_var.c
  src/pk_var.h
  src/pk_vm.c
Labels: refector

#101 class implemented
  Makefile
  README.md
  cli/main.c
  cli/modules/path.c
  cli/repl.c
  docs/TODO.txt
  src/include/pocketlang.h
  src/pk_common.h
  src/pk_compiler.c
  src/pk_core.c
  src/pk_debug.c
  src/pk_opcodes.h
  src/pk_var.c
  src/pk_var.h
  src/pk_vm.c
  tests/lang/class.pk
  tests/lang/import.pk
  tests/tests.py
Labels: enhancement, implementation, refector

#104 Update README.md
  README.md
Labels: documentation

#102 Native types & File object implementations.
  cli/all.c
  cli/common.h
  cli/internal.h
  cli/main.c
  cli/modules.c
  cli/modules.h
  cli/modules/path.c
  cli/repl.c
  cli/thirdparty.c
  cli/thirdparty/cwalk/LICENSE.md
  cli/thirdparty/cwalk/cwalk.c
  cli/thirdparty/cwalk/cwalk.h
  cli/thirdparty/dirent/LICENSE
  cli/thirdparty/dirent/dirent.h
  cli/utils.h
  src/include/pocketlang.h
  src/pk_buffers.h
  src/pk_common.h
  src/pk_compiler.h
  src/pk_core.c
  src/pk_core.h
  src/pk_debug.h
  src/pk_internal.h
  src/pk_utils.h
  src/pk_var.c
  src/pk_var.h
  src/pk_vm.c
  src/pk_vm.h
  tests/check.py
Labels: enhancement, implementation

#107 Typo fix
  README.md
Labels: documentation

#112 Fix #97
  src/pk_compiler.c
  tests/lang/basics.pk
Labels: implementation

#113 Move fiber to module Fiber
  docs/TODO.txt
  docs/pages/Getting-Started/learn-in-15-minutes.md
  docs/pages/Language-API/fibers.md
  src/pk_core.c
  tests/lang/fibers.pk
Labels: refector

#106 Number literal parsing
  src/pk_compiler.c
  tests/lang/basics.pk
Labels: enhancement, implementation

#115 Docs generation refactored.
  README.md
  docs/generate.py
  docs/pages/Getting-Started/build-from-source.md
  docs/pages/Getting-Started/learn-in-15-minutes.md
  docs/try/compile.py
  docs/try/io_api.js
  docs/try/main.c
  docs/try/try_now.js
  src/pk_compiler.c
  src/pk_core.c
  tests/check.py
Labels: refector

#117 in test (ie. elem in container) implemented.
  src/pk_compiler.c
  src/pk_core.c
  src/pk_core.h
  src/pk_vm.c
  tests/lang/basics.pk
Labels: implementation

#119 Add <<= and >>= operators
  src/pk_compiler.c
  tests/lang/basics.pk
Labels: implementation

#121 add elem in map
  src/pk_core.c
  tests/lang/basics.pk
Labels: implementation

#127 Add `IS_NUM_BYTE` validator to check if number is a byte
  src/pk_core.c
Labels: enhancement

#128 Yet another fix of typos
  src/pk_var.c
Labels: documentation

#136 CLI argparse implementation.
  build.bat
  cli/main.c
  cli/repl.c
  cli/thirdparty.c
  cli/thirdparty/argparse/LICENSE
  cli/thirdparty/argparse/argparse.c
  cli/thirdparty/argparse/argparse.h
  docs/TODO.txt
Labels: enhancement

#139 Fix typo in index description
  index.html
Labels: documentation

#126 Add support for hyperbolic & arc trigonometric functions
  src/pk_core.c
  tests/lang/core.pk
Labels: implementation

#144 Fix gcc warning thrown to STDOUT about argv qualifier
  cli/main.c
Labels: bits and pieces

#146 doc: add a better phrase to credit wren
  README.md
Labels: documentation

#138 add exit() function
  src/pk_core.c
Labels: enhancement, implementation

#153 native API function improvements
  cli/modules.c
  cli/modules.h
  src/include/pocketlang.h
  src/pk_core.c
  src/pk_internal.h
  src/pk_var.c
  src/pk_var.h
  tests/check.py
  tests/lang/core.pk
  tests/native/README.md
  tests/native/example.c
Labels: enhancement, implementation
