Repository ThakeeNathees/pocketlang, pull requests merged in 2022-03, with the labels that each got.

#160 Added new Math functions
  src/pk_core.c
  tests/lang/core.pk
Labels: implementation

#167 docs: Fix a few typos
  README.md
  cli/modules.c
  src/pk_compiler.c
  src/pk_core.c
  src/pk_opcodes.h
  src/pk_vm.h
  tests/benchmarks/benchmarks.py
Labels: bits and pieces

#169 some comments were added
  cli/modules.c
  docs/TODO.txt
  src/include/pocketlang.h
  src/pk_compiler.c
  src/pk_core.c
  src/pk_core.h
  src/pk_var.c
  src/pk_var.h
Labels: bits and pieces

#164 Remove find dependency in Makefile
  Makefile
Labels: portability, bits and pieces

#170 Function type validation was always passed - fixed
  src/pk_core.c
Labels: bug
