Repository ThakeeNathees/pocketlang, pull requests merged in 2022-04, with the labels that each got.

#172 copyright notice updated
  LICENSE
  README.md
  build.bat
  cli/common.h
  cli/internal.h
  cli/main.c
  cli/modules.c
  cli/modules.h
  cli/repl.c
  cli/thirdparty.c
  cli/utils.c
  cli/utils.h
  src/include/pocketlang.h
  src/pk_buffers.h
  src/pk_common.h
  src/pk_compiler.c
  src/pk_compiler.h
  src/pk_core.c
  src/pk_core.h
  src/pk_debug.c
  src/pk_debug.h
  src/pk_internal.h
  src/pk_opcodes.h
  src/pk_utils.c
  src/pk_utils.h
  src/pk_var.c
  src/pk_var.h
  src/pk_vm.c
  src/pk_vm.h
Labels: bits and pieces

#173 Compile time stack size wrong calculation fixed.
  src/pk_compiler.c
  src/pk_core.c
  src/pk_debug.c
  src/pk_opcodes.h
  src/pk_vm.c
Labels: bug

#174 un used functions were removed
  src/pk_compiler.c
  src/pk_vm.c
  tests/lang/basics.pk
  tests/lang/functions.pk
  tests/lang/import.pk
  tests/lang/toc.pk
Labels: bug, refector

#175 docs were fully refactored
  README.md
  docs/.gitignore
  docs/TODO.txt
  docs/generate.py
  docs/index.html
  docs/markdown/Api-Docs/Fiber.md
  docs/markdown/Api-Docs/Module.md
  docs/markdown/Reference/Build-From-Source.md
  docs/markdown/Reference/Cheat-Sheet.md
  docs/markdown/Reference/Getting-Started.md
  docs/markdown/Reference/Installation.md
  docs/markdown/template.html
  docs/pages/Getting-Started/build-from-source.md
  docs/pages/Getting-Started/contributing.md
  docs/pages/Getting-Started/try-it-now.html
  docs/pages/Language-API/functions.md
  docs/pages/Language-API/variables.md
  docs/pages/home.md
  docs/static/codejar/style.css
  docs/static/css/docs.css
  docs/static/css/home.css
  docs/static/css/style.css
  docs/static/highlight.js/LICENSE
  docs/static/highlight.js/colors.css
  docs/static/highlight.js/highlight.min.js
  docs/static/icon.png
  docs/static/img/concurrent.svg
  docs/static/img/favicon.svg
  docs/static/img/gc.svg
  docs/static/img/gear.svg
  docs/static/img/logo-white.svg
  docs/static/img/pocketlang.svg
  docs/static/img/repl.svg
  docs/static/js/docs.js
  docs/static/js/home.js
  docs/static/main.css
  docs/static/pygments.css
  docs/static/template.html
  docs/try/compile.py
  docs/try/try_now.js
  docs/wasm/README.md
  docs/wasm/compile.py
  docs/wasm/io_api.js
  docs/wasm/main.c
  tests/benchmarks/tco/toc.pk
  tests/check.py
  tests/lang/tco.pk
Labels: documentation, refector

#178 String interpolation
  README.md
  src/pk_compiler.c
  src/pk_core.c
  tests/lang/basics.pk
  tests/lang/builtin_fn.pk
  tests/tests.py
Labels: enhancement, implementation

#179 Docs try online
  docs/generate.py
  docs/index.html
  docs/static/codejar/style.css
  docs/static/css/docs.css
  docs/static/css/home.css
  docs/static/css/navbar.css
  docs/static/css/style.css
  docs/static/css/try_online.css
  docs/static/highlight.js/theme_dark.css
  docs/static/highlight.js/theme_docs.css
  docs/static/img/favicon.svg
  docs/static/img/logo-white.svg
  docs/static/img/pocketlang.svg
  docs/static/js/docs.js
  docs/static/js/home.js
  docs/static/js/main.js
  docs/static/js/try_online.js
  docs/templates/docs.html
  docs/templates/index.html
  docs/templates/try-online.html
Labels: documentation, enhancement, refector

#183 pk_var changed to pk_value and some minor changes
  cli/common.h
  cli/repl.c
  docs/wasm/main.c
  src/include/pocketlang.h
  src/pk_buffers.h
  src/pk_common.h
  src/pk_compiler.c
  src/pk_compiler.h
  src/pk_core.c
  src/pk_core.h
  src/pk_debug.c
  src/pk_debug.h
  src/pk_internal.h
  src/pk_utils.h
  src/pk_value.c
  src/pk_value.h
  src/pk_vm.h
  tests/check.py
  tests/tests.py
Labels: bits and pieces

#184 parsing context are moved to struct Parser
  src/pk_compiler.c
Labels: refector

#186 debug dump are now directly prints to stdout
  src/pk_compiler.c
  src/pk_core.c
  src/pk_debug.c
  src/pk_debug.h
  src/pk_internal.h
  src/pk_vm.c
Labels: refector

#187 closure and upvalue type were added.
  README.md
  src/pk_core.c
  src/pk_value.c
  src/pk_value.h
  src/pk_vm.c
Labels: implementation

#189 literals renamed to constants
  src/pk_compiler.c
  src/pk_core.c
  src/pk_debug.c
  src/pk_value.c
  src/pk_value.h
  src/pk_vm.c
Labels: bits and pieces

#190 functions and classes are moved to constants buffer
  cli/repl.c
  src/include/pocketlang.h
  src/pk_compiler.c
  src/pk_compiler.h
  src/pk_core.c
  src/pk_debug.c
  src/pk_opcodes.h
  src/pk_value.c
  src/pk_value.h
  src/pk_vm.c
  tests/examples/brainfuck.pk
  tests/lang/functions.pk
  tests/lang/import/globals.pk
  tests/lang/import/globals2.pk
  tests/random/lisp_eval.pk
Labels: enhancement, refector

#192 Scripts renamed to Modules
  cli/internal.h
  src/include/pocketlang.h
  src/pk_compiler.c
  src/pk_compiler.h
  src/pk_core.c
  src/pk_core.h
  src/pk_debug.c
  src/pk_value.c
  src/pk_value.h
  src/pk_vm.c
  src/pk_vm.h
Labels: refector

#193 functions are replaced with closures
  src/include/pocketlang.h
  src/pk_compiler.c
  src/pk_core.c
  src/pk_core.h
  src/pk_debug.c
  src/pk_opcodes.h
  src/pk_value.c
  src/pk_value.h
  src/pk_vm.c
  src/pk_vm.h
Labels: implementation

#194 local variable index miss-calculation bug fix
  src/pk_compiler.c
  tests/lang/functions.pk
Labels: bug

#195 exprName re-defined
  src/pk_compiler.c
Labels: enhancement

#196 Closures implemented
  cli/main.c
  src/pk_compiler.c
  src/pk_debug.c
  src/pk_internal.h
  src/pk_opcodes.h
  src/pk_value.c
  src/pk_value.h
  src/pk_vm.c
  tests/lang/closure.pk
  tests/tests.py
Labels: implementation

#197 fiber pointer stored as register variable
  .gitignore
  docs/.gitignore
  src/pk_vm.c
  tests/benchmarks/benchmarks.py
  tests/benchmarks/list/list.lua
  tests/benchmarks/list/list.pk
  tests/benchmarks/list/list.py
  tests/benchmarks/list/list.rb
  tests/benchmarks/list/list.wren
  tests/benchmarks/tco/tco.pk
Labels: performance

#198 Yet another refactor.
  cli/common.h
  src/include/pocketlang.h
  src/pk_common.h
  src/pk_compiler.c
  src/pk_core.c
  src/pk_internal.h
  src/pk_value.c
  src/pk_value.h
  tests/check.py
  tests/tests.py
Labels: bits and pieces

#199 modules were moved to cli/modules
  cli/all.c
  cli/internal.h
  cli/main.c
  cli/modules/common.h
  cli/modules/modules.c
  cli/modules/modules.h
  cli/modules/std_file.c
  cli/modules/std_path.c
  cli/modules/thirdparty/cwalk/LICENSE.md
  cli/modules/thirdparty/cwalk/cwalk.c
  cli/modules/thirdparty/cwalk/cwalk.h
  cli/modules/thirdparty/dirent/LICENSE
  cli/modules/thirdparty/dirent/dirent.h
  cli/modules/thirdparty/dlfcn-win32/COPYING
  cli/modules/thirdparty/dlfcn-win32/dlfcn.c
  cli/modules/thirdparty/dlfcn-win32/dlfcn.h
  cli/native.py
  cli/thirdparty.c
  src/pk_compiler.c
  src/pk_value.c
  src/pk_vm.c
  tests/check.py
Labels: refector

#201 tcc build supported.
  cli/thirdparty/argparse/argparse.c
  src/pk_core.c
  tests/lang/core.pk
Labels: portability

#200 Fix #105
  cli/repl.c
Labels: portability

#202 More refactors
  cli/all.c
  cli/modules/std_file.c
  cli/modules/std_path.c
  cli/native.py
  cli/thirdparty/argparse/argparse.c
  src/include/pocketlang.h
  src/pk_compiler.c
  src/pk_core.c
  src/pk_core.h
  src/pk_debug.c
  src/pk_value.c
  src/pk_value.h
  src/pk_vm.c
  src/pk_vm.h
Labels: enhancement, refector

#203 function and else if keywords are changed.
  src/pk_compiler.c
  tests/examples/brainfuck.pk
  tests/examples/fizzbuzz.pk
  tests/examples/matrix.pk
  tests/examples/palette.pk
  tests/lang/basics.pk
  tests/lang/closure.pk
  tests/lang/controlflow.pk
  tests/lang/core.pk
  tests/lang/functions.pk
  tests/random/lisp_eval.pk
  tests/tests.py
Labels: bits and pieces

#205 dlfcn removed and minor code cleanups
  cli/all.c
  cli/modules/thirdparty/dlfcn-win32/COPYING
  cli/modules/thirdparty/dlfcn-win32/dlfcn.c
  cli/modules/thirdparty/dlfcn-win32/dlfcn.h
  cli/native.py
  cli/repl.c
  src/include/pocketlang.h
  src/pk_compiler.c
  src/pk_core.c
  src/pk_debug.c
  src/pk_value.c
  src/pk_value.h
  src/pk_vm.c
  src/pk_vm.h
Labels: bits and pieces

#206 [WIP] class implementation
  cli/all.c
  cli/main.c
  cli/modules/modules.c
  cli/modules/modules.h
  cli/modules/std_io.c
  cli/modules/std_math.c
  cli/modules/std_path.c
  src/include/pocketlang.h
  src/pk_compiler.c
  src/pk_core.c
  src/pk_core.h
  src/pk_debug.c
  src/pk_opcodes.h
  src/pk_value.c
  src/pk_value.h
  src/pk_vm.c
  tests/examples/brainfuck.pk
  tests/examples/pi.pk
  tests/lang/basics.pk
  tests/lang/class.pk
  tests/lang/core.pk
  tests/lang/fibers.pk
  tests/lang/import.pk
  tests/modules/math.pk
  tests/native/README.md
  tests/native/example1.c
  tests/native/example2.c
  tests/random/linked_list.pk
  tests/random/lisp_eval.pk
  tests/tests.py
Labels: enhancement, implementation, refector

#207 error pretty print (print lines) implemented
  cli/internal.h
  cli/main.c
  docs/wasm/io_api.js
  docs/wasm/main.c
  src/include/pocketlang.h
  src/pk_compiler.c
  src/pk_core.c
  src/pk_debug.c
  src/pk_debug.h
  src/pk_internal.h
  src/pk_value.c
  src/pk_vm.c
  tests/native/example1.c
  tests/native/example2.c
Labels: bits and pieces

#209 site removed and added an under construction msg.
  404.html
  docs/v0.1.0/Api-Docs/Fiber.html
  docs/v0.1.0/Api-Docs/Module.html
  docs/v0.1.0/Reference/Build-From-Source.html
  docs/v0.1.0/Reference/Cheat-Sheet.html
  docs/v0.1.0/Reference/Getting-Started.html
  docs/v0.1.0/Reference/Installation.html
  index.html
  static/codejar/LICENSE
  static/codejar/README.md
  static/codejar/codejar.js
  static/codejar/linenumbers.js
  static/css/docs.css
  static/css/home.css
  static/css/navbar.css
  static/css/style.css
  static/css/try_online.css
  static/highlight.js/LICENSE
  static/highlight.js/highlight.min.js
  static/highlight.js/theme_dark.css
  static/highlight.js/theme_docs.css
  static/img/concurrent.svg
  static/img/favicon.svg
  static/img/gc.svg
  static/img/gear.svg
  static/img/pocketlang.svg
  static/img/repl.svg
  static/js/docs.js
  static/js/home.js
  static/js/main.js
  static/js/try_online.js
  static/prism/prism.css
  static/prism/prism.js
  static/rage_font/RAGE_1.woff
  static/rage_font/style.css
  static/wasm/pocketlang.html
  static/wasm/pocketlang.js
  static/wasm/pocketlang.wasm
  try-online.html
Labels: documentation

#208 Native interface refactored into slots.
  cli/main.c
  cli/modules/std_io.c
  cli/modules/std_math.c
  cli/modules/std_path.c
  src/include/pocketlang.h
  src/pk_compiler.c
  src/pk_compiler.h
  src/pk_core.c
  src/pk_core.h
  src/pk_debug.c
  src/pk_public.c
  src/pk_value.c
  src/pk_value.h
  src/pk_vm.c
  src/pk_vm.h
  tests/native/example1.c
Labels: implementation, refector

#210 functions and classes are runtime initialized
  src/pk_compiler.c
  src/pk_debug.c
  src/pk_opcodes.h
  src/pk_vm.c
Labels: enhancement

#211 inheritance and 'is' test implemented
  src/pk_compiler.c
  src/pk_core.c
  src/pk_core.h
  src/pk_debug.c
  src/pk_opcodes.h
  src/pk_vm.c
  tests/lang/class.pk
Labels: implementation

#214 class without constructor crash fix
  src/pk_vm.c
  tests/lang/class.pk
Labels: bug

#212 runFunction() abstraction to hide fiber creation
  cli/repl.c
  docs/wasm/main.c
  src/include/pocketlang.h
  src/pk_core.c
  src/pk_public.c
  src/pk_value.h
  src/pk_vm.c
  src/pk_vm.h
Labels: enhancement
